WebClient/Controllers/BlogController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebClient.Models;

namespace WebClient.Controllers;

public class BlogController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public BlogController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }
}

WebClient/Views/Shared/Components/Styles/StylesViewComponent.cs
using BlazorComponents.Library;
using Microsoft.AspNetCore.Mvc;

namespace WebClient.Views.Shared.Components.Styles;

public class StylesViewComponent : ViewComponent
{
    Dictionary<string, string> DefaultStyles = new()
    {
        /* Custom */
        { "--primary", "#072344" },
        { "--secondary", "#00aaa1" },
        /* Slate */
        {"--color-slate-50", "#F7FAFC"},
        {"--color-slate-100", "#EDF2F7"},
        {"--color-slate-200", "#E2E8F0"},
        {"--color-slate-300", "#CBD5E0"},
        {"--color-slate-400", "#A0AEC0"},
        {"--color-slate-500", "#718096"},
        {"--color-slate-600", "#4A5568"},
        {"--color-slate-700", "#2D3748"},
        {"--color-slate-800", "#1A202C"},
        {"--color-slate-900", "#171923"},
        /* Zinc */
        {"--color-zinc-50", "#F9FAFB"},
        {"--color-zinc-100", "#F3F4F6"},
        {"--color-zinc-200", "#E5E7EB"},
        {"--color-zinc-300", "#D1D5DB"},
        {"--color-zinc-400", "#9CA3AF"},
        {"--color-zinc-500", "#6B7280"},
        {"--color-zinc-600", "#4B5563"},
        {"--color-zinc-700", "#374151"},
        {"--color-zinc-800", "#1F2937"},
        {"--color-zinc-900", "#111827"},
        /* Neutral */
        {"--color-neutral-50", "#FAFAFA"},
        {"--color-neutral-100", "#F4F4F5"},
        {"--color-neutral-200", "#E4E4E7"},
        {"--color-neutral-300", "#D4D4D8"},
        {"--color-neutral-400", "#A1A1AA"},
        {"--color-neutral-500", "#71717A"},
        {"--color-neutral-600", "#52525B"},
        {"--color-neutral-700", "#3F3F46"},
        {"--color-neutral-800", "#27272A"},
        {"--color-neutral-900", "#18181B"},
        /* Stone */
        {"--color-stone-50", "#FCFBF7"},
        {"--color-stone-100", "#F7F3E9"},
        {"--color-stone-200", "#EDE6D3"},
        {"--color-stone-300", "#DDD1B9"},
        {"--color-stone-400", "#C7B299"},
        {"--color-stone-500", "#A3866A"},
        {"--color-stone-600", "#7F5A3F"},
        {"--color-stone-700", "#583517"},
        {"--color-stone-800", "#391F0D"},
        {"--color-stone-900", "#1E0F05"},
        /* Grays */
        { "--color-gray-50", "#f9fafb" },
        { "--color-gray-100", "#f3f4f6" },
        { "--color-gray-200", "#e5e7eb" },
        { "--color-gray-300", "#d1d5db" },
        { "--color-gray-400", "#9ca3af" },
        { "--color-gray-500", "#6b7280" },
        { "--color-gray-600", "#4b5563" },
        { "--color-gray-700", "#374151" },
        { "--color-gray-800", "#1f2937" },
        { "--color-gray-900", "#111827" },
        /* Reds */
        { "--color-red-50", "#fef2f2" },
        { "--color-red-100", "#fee2e2" },
        { "--color-red-200", "#fecaca" },
        { "--color-red-300", "#fca5a5" },
        { "--color-red-400", "#f87171" },
        { "--color-red-500", "#ef4444" },
        { "--color-red-600", "#dc2626" },
        { "--color-red-700", "#b91c1c" },
        { "--color-red-800", "#991b1b" },
        { "--color-red-900", "#7f1d1d" },
        /* Orange */
        {"--color-orange-50", "#FFF7ED"},
        {"--color-orange-100", "#FFEDD5"},
        {"--color-orange-200", "#FED7AA"},
        {"--color-orange-300", "#FDBA74"},
        {"--color-orange-400", "#FB923C"},
        {"--color-orange-500", "#F97316"},
        {"--color-orange-600", "#EA580C"},
        {"--color-orange-700", "#C2410C"},
        {"--color-orange-800", "#9A3412"},
        {"--color-orange-900", "#7C2D12"},
        /* Amber */
        {"--color-amber-50", "#FFFBEB"},
        {"--color-amber-100", "#FEF3C7"},
        {"--color-amber-200", "#FDE68A"},
        {"--color-amber-300", "#FCD34D"},
        {"--color-amber-400", "#FBBF24"},
        {"--color-amber-500", "#F59E0B"},
        {"--color-amber-600", "#D97706"},
        {"--color-amber-700", "#B45309"},
        {"--color-amber-800", "#92400E"},
        {"--color-amber-900", "#78350F"},
        /* Yellows */
        { "--color-yellow-50", "#fffbeb" },
        { "--color-yellow-100", "#fef3c7" },
        { "--color-yellow-200", "#fde68a" },
        { "--color-yellow-300", "#fcd34d" },
        { "--color-yellow-400", "#fbbf24" },
        { "--color-yellow-500", "#f59e0b" },
        { "--color-yellow-600", "#d97706" },
        { "--color-yellow-700", "#b45309" },
        { "--color-yellow-800", "#92400e" },
        { "--color-yellow-900", "#78350f" },
        /* Lime */
        {"--color-lime-50", "#F7FEE7"},
        {"--color-lime-100", "#ECFCCB"},
        {"--color-lime-200", "#D9F99D"},
        {"--color-lime-300", "#BEF264"},
        {"--color-lime-400", "#A3E635"},
        {"--color-lime-500", "#84CC16"},
        {"--color-lime-600", "#65A30D"},
        {"--color-lime-700", "#4D7C0F"},
        {"--color-lime-800", "#3F6212"},
        {"--color-lime-900", "#365314"},
        /* Greens */
        { "--color-green-50", "#ecfdf5" },
        { "--color-green-100", "#d1fae5" },
        { "--color-green-200", "#a7f3d0" },
        { "--color-green-300", "#6ee7b7" },
        { "--color-green-400", "#34d399" },
        { "--color-green-500", "#10b981" },
        { "--color-green-600", "#059669" },
        { "--color-green-700", "#047857" },
        { "--color-green-800", "#065f46" },
        { "--color-green-900", "#064e3b" },
        /* Emerald */
        {"--color-emerald-50", "#ECFDF5"},
        {"--color-emerald-100", "#D1FAE5"},
        {"--color-emerald-200", "#A7F3D0"},
        {"--color-emerald-300", "#6EE7B7"},
        {"--color-emerald-400", "#34D399"},
        {"--color-emerald-500", "#10B981"},
        {"--color-emerald-600", "#059669"},
        {"--color-emerald-700", "#047857"},
        {"--color-emerald-800", "#065F46"},
        {"--color-emerald-900", "#064E3B"},
        /* Teal */     
        {"--color-teal-50", "#F0FDFA"},
        {"--color-teal-100", "#CCFBF1"},
        {"--color-teal-200", "#99F6E4"},
        {"--color-teal-300", "#5EEAD4"},
        {"--color-teal-400", "#2DD4BF"},
        {"--color-teal-500", "#14B8A6"},
        {"--color-teal-600", "#0D9488"},
        {"--color-teal-700", "#0F766E"},
        {"--color-teal-800", "#115E59"},
        {"--color-teal-900", "#134E4A"},
        /* Cyan */
        {"--color-cyan-50", "#EDFDFD"},
        {"--color-cyan-100", "#C4F1F9"},
        {"--color-cyan-200", "#9DECF9"},
        {"--color-cyan-300", "#76E4F7"},
        {"--color-cyan-400", "#0BC5EA"},
        {"--color-cyan-500", "#00B5D8"},
        {"--color-cyan-600", "#00A3C4"},
        {"--color-cyan-700", "#0987A0"},
        {"--color-cyan-800", "#086F83"},
        {"--color-cyan-900", "#065666"},
        /* Sky */
        {"--color-sky-50", "#F0F9FF"},
        {"--color-sky-100", "#E0F2FE"},
        {"--color-sky-200", "#BAE6FD"},
        {"--color-sky-300", "#7DD3FC"},
        {"--color-sky-400", "#38BDF8"},
        {"--color-sky-500", "#0EA5E9"},
        {"--color-sky-600", "#0284C7"},
        {"--color-sky-700", "#0369A1"},
        {"--color-sky-800", "#075985"},
        {"--color-sky-900", "#0C4A6E"},
        /* Blues */
        { "--color-blue-50", "#eff6ff" },
        { "--color-blue-100", "#dbeafe" },
        { "--color-blue-200", "#bfdbfe" },
        { "--color-blue-300", "#93c5fd" },
        { "--color-blue-400", "#60a5fa" },
        { "--color-blue-500", "#3b82f6" },
        { "--color-blue-600", "#2563eb" },
        { "--color-blue-700", "#1d4ed8" },
        { "--color-blue-800", "#1e40af" },
        { "--color-blue-900", "#1e3a8a" },
        /* Indigos */
        {"--color-indigo-50", "#eef2ff"},
        {"--color-indigo-100", "#e0e7ff"},
        {"--color-indigo-200", "#c7d2fe"},
        {"--color-indigo-300", "#a5b4fc"},
        {"--color-indigo-400", "#818cf8"},
        {"--color-indigo-500", "#6366f1"},
        {"--color-indigo-600", "#4f46e5"},
        {"--color-indigo-700", "#4338ca"},
        {"--color-indigo-800", "#3730a3"},
        {"--color-indigo-900", "#312e81"},
        /* Violet */
        {"--color-violet-50", "#F5F3FF"},
        {"--color-violet-100", "#EDE9FE"},
        {"--color-violet-200", "#DDD6FE"},
        {"--color-violet-300", "#C4B5FD"},
        {"--color-violet-400", "#A78BFA"},
        {"--color-violet-500", "#8B5CF6"},
        {"--color-violet-600", "#7C3AED"},
        {"--color-violet-700", "#6D28D9"},
        {"--color-violet-800", "#5B21B6"},
        {"--color-violet-900", "#4C1D95"},
        /* Purples */
        {"--color-purple-50", "#f5f3ff"},
        {"--color-purple-100", "#ede9fe"},
        {"--color-purple-200", "#ddd6fe"},
        {"--color-purple-300", "#c4b5fd"},
        {"--color-purple-400", "#a78bfa"},
        {"--color-purple-500", "#8b5cf6"},
        {"--color-purple-600", "#7c3aed"},
        {"--color-purple-700", "#6d28d9"},
        {"--color-purple-800", "#5b21b6"},
        {"--color-purple-900", "#4c1d95"},
        /* Pinks */
        {"--color-pink-50", "#fdf2f8"},
        {"--color-pink-100", "#fce7f3"},
        {"--color-pink-200", "#fbcfe8"},
        {"--color-pink-300", "#f9a8d4"},
        {"--color-pink-400", "#f472b6"},
        {"--color-pink-500", "#ec4899"},
        {"--color-pink-600", "#db2777"},
        {"--color-pink-700", "#be185d"},
        {"--color-pink-800", "#9d174d"},
        {"--color-pink-900", "#831843"},
        /* Fuchsia */
        {"--color-fuchsia-50", "#FDF4FF"},
        {"--color-fuchsia-100", "#FAE8FF"},
        {"--color-fuchsia-200", "#F5D0FE"},
        {"--color-fuchsia-300", "#F0ABFC"},
        {"--color-fuchsia-400", "#E879F9"},
        {"--color-fuchsia-500", "#D946EF"},
        {"--color-fuchsia-600", "#C026D3"},
        {"--color-fuchsia-700", "#A21CAF"},
        {"--color-fuchsia-800", "#86198F"},
        {"--color-fuchsia-900", "#701A75"},
        /* Rose */
        {"--color-rose-50", "#FFF1F2"},
        {"--color-rose-100", "#FFE4E6"},
        {"--color-rose-200", "#FECDD3"},
        {"--color-rose-300", "#FDA4AF"},
        {"--color-rose-400", "#FB7185"},
        {"--color-rose-500", "#F43F5E"},
        {"--color-rose-600", "#E11D48"},

WebClient/Views/Shared/_FooterPartial.cshtml
<div class="container mx-auto px-4">
    <div class="flex items-center justify-between border-t border-gray-300 py-10 flex-row sm:py-12">
        <a href="/" class="mr-auto sm:mr-6">
            <i class="fa-solid fa-2x fa-anchor"></i>
        </a>
        <p class="font-body font-light text-primary">
            .NET Adaptation by Victor Pérez Asuaje.
        </p>
    </div>
</div>

WebClient/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebClient</title>
    <link rel="stylesheet" href="~/css/styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebClient.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.css" rel="stylesheet" />

    @await Component.InvokeAsync("Styles")

</head>
<body>
    <partial name="_MenuPartial" />

    <main id="main" role="main" class="container mx-auto px-4">
        @RenderBody()
    </main>

    <partial name="_FooterPartial" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.4/flowbite.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebClient/Views/Shared/_MenuPartial.cshtml
<nav class="bg-white border-gray-200 px-4 py-2.5 rounded dark:bg-gray-900">
    <div class="container flex flex-wrap items-center justify-between mx-auto">
        <a asp-controller="Home" asp-action="Index" class="flex items-center">
            <i class="fa-solid fa-2x fa-anchor"></i>
        </a>

        <div class="flex">
            <div class="items-center justify-between flex w-auto">
                <ul class="flex flex-row p-4 mt-4 rounded-lg border-0 space-x-8 mt-0 text-sm font-medium">
                    <li>
                        <a asp-controller="Blog" asp-action="Index" class="block py-2 pl-3 pr-4 text-primary hover:text-purple-500 rounded md:bg-transparent md:p-0" aria-current="page">Blog</a>
                    </li>
                </ul>
            </div>

            <!-- User menu -->

            <div class="flex items-center ml-3">
                <button type="button" class="flex mr-3 text-sm rounded-full p-2 md:mr-0 focus:ring-4 focus:ring-gray-300 hover:text-gray-900 hover:bg-gray-100" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
                    <i class="fa-solid fa-user"></i>
                </button>
                <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow" id="user-dropdown">
                    <div class="px-4 py-3">
                        <span class="block text-sm text-gray-900">Joe Doe</span>
                        <span class="block text-sm font-medium text-gray-500 truncate">joedoe@sample.com</span>
                    </div>
                    <ul class="py-2" aria-labelledby="user-menu-button">
                        <li>
                            <a href="#Dashboard" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Dashboard</a>
                        </li>
                        <li>
                            <a href="#Settings" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Settings</a>
                        </li>
                        <li>
                            <a href="#Earnings" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Earnings</a>
                        </li>
                        <li>
                            <a href="#Signout" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">Sign out</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</nav>